CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  vip INTEGER NOT NULL DEFAULT 0,
  balance INTEGER NOT NULL DEFAULT 1200,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
